# Generated by Django 5.2.6 on 2025-09-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCrawlingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(help_text='크롤링에 사용된 검색어', max_length=200, verbose_name='검색어')),
                ('total_found', models.IntegerField(help_text='네이버 API에서 반환한 총 결과 개수', verbose_name='총 검색 결과')),
                ('total_crawled', models.IntegerField(help_text='실제로 가져온 뉴스 개수', verbose_name='크롤링된 개수')),
                ('total_saved', models.IntegerField(help_text='중복 제거 후 DB에 저장된 개수', verbose_name='저장된 개수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='크롤링 일시')),
                ('status', models.CharField(choices=[('SUCCESS', '성공'), ('PARTIAL', '부분 성공'), ('FAILED', '실패')], default='SUCCESS', max_length=20, verbose_name='크롤링 상태')),
                ('error_message', models.TextField(blank=True, help_text='크롤링 중 발생한 오류 내용', null=True, verbose_name='오류 메시지')),
            ],
            options={
                'verbose_name': '크롤링 로그',
                'verbose_name_plural': '크롤링 로그들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='네이버 API에서 가져온 뉴스 제목', max_length=500, verbose_name='뉴스 제목')),
                ('description', models.TextField(help_text='네이버 API에서 제공하는 뉴스 요약 내용', verbose_name='뉴스 요약')),
                ('link', models.URLField(help_text='네이버 뉴스 링크', max_length=1000, verbose_name='뉴스 링크')),
                ('original_link', models.URLField(blank=True, help_text='원본 언론사 링크', max_length=1000, null=True, verbose_name='원본 링크')),
                ('pub_date', models.CharField(help_text='네이버 API에서 제공하는 발행일시 (원본 형식)', max_length=100, verbose_name='발행일시')),
                ('publisher', models.CharField(blank=True, help_text='뉴스 발행처/언론사명', max_length=200, null=True, verbose_name='발행처')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='DB에 저장된 일시', verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='마지막 수정 일시', verbose_name='수정일시')),
                ('content_hash', models.CharField(help_text='제목+링크 기반 해시값 (중복 방지용)', max_length=64, unique=True, verbose_name='콘텐츠 해시')),
            ],
            options={
                'verbose_name': '뉴스 기사',
                'verbose_name_plural': '뉴스 기사들',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['publisher'], name='crawlings_n_publish_aa4868_idx'), models.Index(fields=['created_at'], name='crawlings_n_created_9b123e_idx'), models.Index(fields=['content_hash'], name='crawlings_n_content_e8d3c5_idx')],
            },
        ),
    ]
