# Generated by Django 5.2.6 on 2025-09-17 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100, verbose_name='종목명')),
                ('stock_code', models.CharField(max_length=20, verbose_name='종목코드')),
                ('quantity', models.PositiveIntegerField(verbose_name='보유수량')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='매입가')),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='보유현금')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포트폴리오',
                'verbose_name_plural': '포트폴리오',
                'db_table': 'portfolio',
                'indexes': [models.Index(fields=['user', 'stock_code'], name='portfolio_user_id_78024d_idx'), models.Index(fields=['created_at'], name='portfolio_created_70a1b1_idx')],
            },
        ),
    ]
