FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        python3-dev \
        && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip setuptools wheel build

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# ENTRYPOINT ["uvicorn", "app.api.endpoints:router", "--host", "0.0.0.0", "--port", "9000"]
ENTRYPOINT ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "9000"]
