FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 7000

CMD ["sh", "-c", "until pg_isready -h $DB_HOST -p $DB_PORT; do echo 'Waiting for postgres...'; sleep 2; done && python manage.py migrate && python manage.py runserver 0.0.0.0:7000"]
